### ISSUE TITLE
Support for preprocessing

### ISSUE THREAD

**Issue by peterschrammel** [marcogario/ipasir#1]
We would like to use IPASIR, but we are a concerned about the required support for using a solver's preprocessor. E.g. MiniSAT and Glucose require a function to freeze variables to enable the use of their preprocessor in combination with incremental solving. Currently, it seems that IPASIR only allows us to use e.g. Glucose without preprocessor, which is not acceptable performance-wise.

**Comment by marcogario** [comment]
I am not sure if I can help you with this. This repository is a demonstration on how to use python cffi to execute an ipasir solver. Maybe you should ask the SAT competition organizers, if you think ipasir should be extended. 

My understanding is that the interface does not prescribes a behavior for preprocessing, and whether the solver is able to perform simplifications when new clauses are added depends on the implementation. You might have better luck talking with the solver developer. 

Please note that ipasir is focused on incremental solving. Some Preprocessing might become unsound for incremental solving, therefore you might have additional restrictions on what you can do. I would recommend that you look into whether you really need ipasir or can use a solver api directly. This would give you some idea of the performance loss (if any).

**Comment by peterschrammel** [comment]
Sorry for having bothered you. Maybe add a README to your repo that points to the original IPASIR repo. Best wishes.
